### ISSUE TITLE
Fuzzywuzzy?

### ISSUE THREAD

**Issue by hrstoyanov** [almondtools/stringbench#9]
Hi,
Can you include/asses this port to Java of Python's fuzzywuzzy search algorithm, please:

https://github.com/xdrop/fuzzywuzzy

It seems like Levenstein distance based, interesting to see how it competes with the others..

Thank you!

**Comment by almondtools** [comment]
fuzzywuzzy is about fuzzy string matching, that means 
- matching two strings
- with a similarity metric

stringbench benchmarks exact string search
- finding multiple strings (needles) in another (haystack)
- only exact matches

The API seems quite different for me, so it is hardly comparable.
